version: "3.8"

services:
  autonity:
    image: ${TAG}
    container_name: autonity
    restart: always
    env_file:
      - $HOME/autonity-node/.env
    volumes:
      - ${DATADIR}:/autonity-chaindata
    command: >
      --datadir=/autonity-chaindata
      --${CHAIN}
      --maxpeers=${PEERS}
      --http
      --http.api="aut,eth,net,txpool,web3,admin"
      --http.vhosts="*"
      --http.addr=${HTTP_ADDR}
      --http.port=8545
      --ws
      --ws.api="aut,eth,net,txpool,web3,admin"
      --ws.addr=${WS_ADDR}
      --ws.port=8546
      --nat extip:${YOUR_IP}
      --metrics
      --metrics.addr=${METRICS_ADDR}
      --metrics.port=6060
      --bootnodes=${BOOTNODES}
    ports:
      - ${HTTP_PORT}:8545 # rpc json
      - ${WS_PORT}:8546 # websocket
      - ${METRICS_PORT}:6060 # metrics
      - ${BOOTNODES_PORT}:30303/tcp # bootnodes
      - ${BOOTNODES_PORT}:30303/udp # bootnodes
    logging:
      driver: json-file
      options:
        max-size: "500m"
        max-file: "20"
    networks:
      - autonity_network

  autonity_oracle:
    image: ${ORACLE_TAG}
    container_name: autonity_oracle
    restart: always
    depends_on:
      - autonity
    env_file:
      - $HOME/autonity-node/.env
    volumes:
      - ${ORACLE_KEYFILE}:/autoracle/oracle.key
      - ${ORACLE_PLUGIN}:/autoracle/plugins-conf.yml
    command: >
      --key.file="/autoracle/oracle.key"
      --key.password="${ORACLE_KEYPASS}"
      --ws="ws://autonity:${WS_PORT}"
      --plugin.dir="/usr/local/bin/plugins/"
      --plugin.conf="/autoracle/plugins-conf.yml"
    logging:
      driver: json-file
      options:
        max-size: "500m"
        max-file: "20"
    networks:
      - autonity_network
      
networks:
  autonity_network:
    external: false
    driver: bridge

volumes:
  autonity-chaindata:
