version: "3.8"

services:
  autonity:
    image: ${ORACLE_TAG}
    container_name: autonity_oracle
    restart: always
    env_file:
      - $HOME/autonity-node/.env
    volumes:
      - ${ORACLE_KEYFILE}:/autoracle/oracle.key
      - ${ORACLE_PLUGIN}:/autoracle/plugins-conf.yml
    command: >
      --key.file="/autoracle/oracle.key"
      --key.password="${ORACLE_KEYPASS}"
      --ws="http://autonity:${WS_PORT}"
      --plugin.dir="/usr/local/bin/plugins/"
      --plugin.conf="/autoracle/plugins-conf.yml"
    logging:
      driver: json-file
      options:
        max-size: "500m"
        max-file: "20"
    networks:
      - autonity

networks:
  autonity:
    external: true
